In [1]:
#import libraries 
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import datetime as dt
sns.set_theme()

In [2]:
df = pd.read_csv('preprocessing.csv',index_col=0)
print(df.shape)
df.head()

(466246, 13)

,crime_type,crime_category,date,reported,y_lon,x_lat,neighborhood,dates,times,equity_score,pop_2010,crime_count,neighborhood_crime_rate
0,criminal-mischief-other,public-disorder,2022-01-04 11:30:00,2022-01-04 20:36:00,-105.018825,39.714268,Valverde,2022-01-04,11:30:00,1.6,3941.0,1,822.633849
1,criminal-mischief-other,public-disorder,2022-01-03 19:47:00,2022-01-03 21:12:00,-105.014892,39.711518,Valverde,2022-01-03,19:47:00,1.6,3941.0,1,822.633849
6,criminal-mischief-other,public-disorder,2019-06-19 16:30:00,2019-06-20 14:21:00,-105.014690,39.712854,Valverde,2019-06-19,16:30:00,1.6,3941.0,1,822.633849
7,criminal-mischief-other,public-disorder,2019-09-11 16:30:00,2019-09-13 14:55:00,-105.012846,39.711710,Valverde,2019-09-11,16:30:00,1.6,3941.0,1,822.633849
8,criminal-mischief-other,public-disorder,2021-11-08 02:42:00,2021-11-08 03:31:00,-105.024081,39.722317,Valverde,2021-11-08,02:42:00,1.6,3941.0,1,822.633849

In [3]:
df = df.iloc[:,[1,4,5,6,8,9]]
df.head()

    crime_category       y_lon      x_lat neighborhood     times  equity_score
0  public-disorder -105.018825  39.714268     Valverde  11:30:00           1.6
1  public-disorder -105.014892  39.711518     Valverde  19:47:00           1.6
6  public-disorder -105.014690  39.712854     Valverde  16:30:00           1.6
7  public-disorder -105.012846  39.711710     Valverde  16:30:00           1.6
8  public-disorder -105.024081  39.722317     Valverde  02:42:00           1.6

In [4]:
df.isnull().sum().sort_values(ascending=False)

crime_category    0
y_lon             0
x_lat             0
neighborhood      0
times             0
equity_score      0
dtype: int64

In [5]:
df.crime_category.value_counts()

traffic-accident                106846
all-other-crimes                 74413
theft-from-motor-vehicle         49760
public-disorder                  49619
larceny                          49587
auto-theft                       39854
burglary                         24244
drug-alcohol                     22630
other-crimes-against-persons     21996
aggravated-assault               13652
robbery                           6327
white-collar-crime                6217
arson                              720
murder                             381
Name: crime_category, dtype: int64

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
y_lon,466246.0,-104.928508,1.793875,-115.46406,-105.004766,-104.980425,-104.916195,5.000000e-07
x_lat,466246.0,39.721679,0.679421,0.00000,39.707754,39.739852,39.760192,3.990431e+01
equity_score,466246.0,2.931285,0.801037,1.60000,2.300000,3.100000,3.600000,4.700000e+00

In [7]:
duplicateRowsDF = df[df.duplicated()]
duplicateRowsDF

,crime_category,y_lon,x_lat,neighborhood,times,equity_score
136,public-disorder,-105.024676,39.712702,Valverde,19:00:00,1.6
138,public-disorder,-105.019777,39.722760,Valverde,07:00:00,1.6
226,public-disorder,-105.018250,39.719334,Valverde,00:01:00,1.6
647,public-disorder,-105.024643,39.721718,Valverde,18:50:00,1.6
651,public-disorder,-105.021706,39.721926,Valverde,22:41:00,1.6
...,...,...,...,...,...,...
428988,white-collar-crime,-104.908082,39.630543,Southmoor Park,00:00:00,3.6
436380,white-collar-crime,-104.916504,39.739921,Montclair,11:52:00,4.2
444427,white-collar-crime,-104.987138,39.698374,Washington Park West,17:00:00,4.2
446842,white-collar-crime,-105.032228,39.790723,Regis,08:00:00,2.4
339206,murder,-104.861964,39.658404,Kennedy,06:30:00,2.8

In [8]:
df.shape

(466246, 6)

In [9]:
factors = ['y_lon', 'x_lat', 'neighborhood','times', 'equity_score']
y=df.crime_category
X=df[factors]
X=pd.get_dummies(X)

In [10]:
from sklearn.model_selection import train_test_split

# dont forget to define your X and y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=1)

In [11]:
#scale data
from sklearn import preprocessing
import numpy as np
# build scaler based on training data and apply it to test data to then also scale the test data
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [12]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import f1_score
from sklearn.metrics import auc
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix,roc_curve,roc_auc_score
from sklearn.metrics import accuracy_score,log_loss
from matplotlib import pyplot as plt

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=300, random_state = 1,n_jobs=-1)
model_res = clf.fit(X_train_scaled, y_train)
y_pred = model_res.predict(X_test_scaled)
y_pred_prob = model_res.predict_proba(X_test_scaled)

In [ ]:
y_pred_prob

In [ ]:
lr_probs = y_pred_prob[:,1]
ac = accuracy_score(y_test, y_pred)

f1 = f1_score(y_test, y_pred, average='weighted')
cm = confusion_matrix(y_test, y_pred)

print('Random Forest: Accuracy=%.3f' % (ac))

print('Random Forest: f1-score=%.3f' % (f1))

In [ ]:
feature_importance = clf.feature_importances_
# make importances relative to max importance
feature_importance = 100.0 * (feature_importance / feature_importance.max())[:30]
sorted_idx = np.argsort(feature_importance)[:30]

pos = np.arange(sorted_idx.shape[0]) + .5
print(pos.size)
sorted_idx.size
plt.figure(figsize=(10,10))
plt.barh(pos, feature_importance[sorted_idx], align='center')
plt.yticks(pos, X.columns[sorted_idx])
plt.xlabel('Relative Importance')
plt.title('Variable Importance')
plt.show()

In [ ]:
# Import xgboost
import xgboost as xgb

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=.2, random_state=123)

# Instantiate the XGBClassifier: xg_cl
xg_cl = xgb.XGBClassifier(objective='binary:logistic', n_estimators=10, seed=123)

# Fit the classifier to the training set
xg_cl.fit(X_train,y_train)

# Predict the labels of the test set: preds
preds = xg_cl.predict(X_test)

# Compute the accuracy: accuracy
accuracy = float(np.sum(preds==y_test))/y_test.shape[0]
print("accuracy: %f" % (accuracy))